// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser (Tick)</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Mail.MailTo" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Mail.Modifiers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Mail.Mapi" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope="member", Target="Atom.Mail.SafeMailSender.#Send(Atom.Mail.IMailMessage)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="MailTo", Scope="namespace", Target="Atom.Mail.MailTo" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="MailTo", Scope="type", Target="Atom.Mail.MailTo.MailToMailSender" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="Atom.Mail.MailTo.MailToMailSender.#Send(Atom.Mail.IMailMessage)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender.#SendDirect(Atom.Mail.IMailMessage)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId="NativeMapiMessage.dateReceived", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender+NativeMethods.#MAPISendMail(System.IntPtr,System.IntPtr,Atom.Mail.Mapi.NativeMapiMessage,System.Int32,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId="NativeMapiMessage.messageType", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender+NativeMethods.#MAPISendMail(System.IntPtr,System.IntPtr,Atom.Mail.Mapi.NativeMapiMessage,System.Int32,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId="NativeMapiMessage.noteText", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender+NativeMethods.#MAPISendMail(System.IntPtr,System.IntPtr,Atom.Mail.Mapi.NativeMapiMessage,System.Int32,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId="NativeMapiMessage.subject", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender+NativeMethods.#MAPISendMail(System.IntPtr,System.IntPtr,Atom.Mail.Mapi.NativeMapiMessage,System.Int32,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId="NativeMapiMessage.conversationID", Scope="member", Target="Atom.Mail.Mapi.MapiMailSender+NativeMethods.#MAPISendMail(System.IntPtr,System.IntPtr,Atom.Mail.Mapi.NativeMapiMessage,System.Int32,System.Int32)" )]
