//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Fmod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Fmod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; of the native fmodex.dll is not supported. &apos;{1}&apos; or newer is required..
        /// </summary>
        internal static string Error_NativeDllVersionXNotSupportedYRequired {
            get {
                return ResourceManager.GetString("Error_NativeDllVersionXNotSupportedYRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native FMODex sound object is null. Consider loading the Sound Resource..
        /// </summary>
        internal static string Error_NativeSoundObjectIsNull {
            get {
                return ResourceManager.GetString("Error_NativeSoundObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource &apos;{0}&apos; doesn&apos;t exist at the file path &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ResourceXAtPathYDoesntExist {
            get {
                return ResourceManager.GetString("Error_ResourceXAtPathYDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AudioSystem is already initialized..
        /// </summary>
        internal static string Error_TheAudioSystemIsAlreadyInitialized {
            get {
                return ResourceManager.GetString("Error_TheAudioSystemIsAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AudioSystem is not initialized..
        /// </summary>
        internal static string Error_TheAudioSystemIsNotInitialized {
            get {
                return ResourceManager.GetString("Error_TheAudioSystemIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ChannelGroup has got no child ChannelGroups..
        /// </summary>
        internal static string Error_TheChannelGroupHasNoChildGroups {
            get {
                return ResourceManager.GetString("Error_TheChannelGroupHasNoChildGroups", resourceCulture);
            }
        }
    }
}
