// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser (Tick)</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId="transform", Scope="member", Target="Atom.Physics.Farseer.RigidBody.#Unhook(Atom.Components.Transform.ITransform2)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Farseer" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Farseer", Scope="namespace", Target="Atom.Physics.Farseer" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId="transform", Scope="member", Target="Atom.Physics.Farseer.RigidBody.#Hook(Atom.Components.Transform.ITransform2)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Physics.Farseer.RigidBody.#BodyChanged" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId="Farseer", Scope="resource", Target="Atom.Physics.Farseer.Properties.Resources.resources" )]
