// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.KeyboardInputEventHandler.#Invoke(System.Object,Microsoft.Xna.Framework.Input.KeyboardState&,Microsoft.Xna.Framework.Input.KeyboardState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="2#", Scope="member", Target="Atom.Xna.UI.KeyboardInputEventHandler.#Invoke(System.Object,Microsoft.Xna.Framework.Input.KeyboardState&,Microsoft.Xna.Framework.Input.KeyboardState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.MouseInputEventHandler.#Invoke(System.Object,Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="2#", Scope="member", Target="Atom.Xna.UI.MouseInputEventHandler.#Invoke(System.Object,Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1021:AvoidOutParameters", MessageId="1#", Scope="member", Target="Atom.Xna.UI.Controls.DynamicSpriteButtonSpriteReceiver.#Invoke(Atom.Xna.UI.Controls.DynamicSpriteButton,Atom.Xna.ISprite&,Atom.Xna.ISprite&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1021:AvoidOutParameters", MessageId="2#", Scope="member", Target="Atom.Xna.UI.Controls.DynamicSpriteButtonSpriteReceiver.#Invoke(Atom.Xna.UI.Controls.DynamicSpriteButton,Atom.Xna.ISprite&,Atom.Xna.ISprite&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.UI.Controls" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="TypeWriter", Scope="type", Target="Atom.Xna.UI.AnimatedTypeWriterText" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.Controls.Button.#Clicked" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope="type", Target="Atom.Xna.UI.Text" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId="text", Scope="member", Target="Atom.Xna.UI.Text.#SplitIntoBlock(System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.Tooltip.#IsTooltipVisible(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.Tooltip.#IsTooltipVisible(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleKeyInput(Microsoft.Xna.Framework.Input.KeyboardState&,Microsoft.Xna.Framework.Input.KeyboardState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleKeyInput(Microsoft.Xna.Framework.Input.KeyboardState&,Microsoft.Xna.Framework.Input.KeyboardState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleMouseInput(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleMouseInput(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleRelatedMouseInput(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.UIElement.#OnMouseOver(Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.UIElement.#HandleRelatedMouseInput(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UIElement.#MouseLeaving" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UIElement.#MouseEntering" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UIElement.#IsVisibleChanged" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UIElement.#IsEnabledChanged" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UIElement.#FloorNumberChanged" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Y", Scope="member", Target="Atom.Xna.UI.UIElement.#Y" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="X", Scope="member", Target="Atom.Xna.UI.UIElement.#X" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId="mouseState", Scope="member", Target="Atom.Xna.UI.UserInterface.#Draw(Atom.Xna.ISpriteDrawContext)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Atom.Xna.UI.UserInterface.#GetCurrentMouseState()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UserInterface.#KeyboardInput" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Xna.UI.UserInterface.#MouseInput" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.Tooltips.Tooltip.#GetTooltipVisability(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.Tooltips.Tooltip.#GetTooltipVisability(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.UI.Tooltips" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.Controls.Button.#Click(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.Controls.Button.#Click(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.UI.Tooltips.Tooltip.#GetTooltipVisibility(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.UI.Tooltips.Tooltip.#GetTooltipVisibility(Microsoft.Xna.Framework.Input.MouseState&,Microsoft.Xna.Framework.Input.MouseState&)" )]
