//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Events {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Game.Events.EventStrings", typeof(EventStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the name of the EventTrigger &apos;{0}&apos; to &apos;{1}&apos;. There already exists such an EventTrigger in the owning Event Manager. EventTrigger names must be unique..
        /// </summary>
        internal static string Error_CantChangeNameOfEventTriggerXToYThereAlreadyExistsSuchAnEventTrigger {
            get {
                return ResourceManager.GetString("Error_CantChangeNameOfEventTriggerXToYThereAlreadyExistsSuchAnEventTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the name of the Event &apos;{0}&apos; to &apos;{1}&apos;. There already exists such an Event in the owning Event Manager. Event names must be unique..
        /// </summary>
        internal static string Error_CantChangeNameOfEventXToYThereAlreadyExistsSuchAnEvent {
            get {
                return ResourceManager.GetString("Error_CantChangeNameOfEventXToYThereAlreadyExistsSuchAnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t do this. The event &apos;{0}&apos; (type-name=&apos;{1}&apos;) has not been added to an EventManager..
        /// </summary>
        internal static string Error_CantDoThisEventXTypeNameYHasNotBeenAddedToManager {
            get {
                return ResourceManager.GetString("Error_CantDoThisEventXTypeNameYHasNotBeenAddedToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EventManager returned by the existing IEventManagerService is null..
        /// </summary>
        internal static string Error_EventManagerReturnedByEventServiceIsNull {
            get {
                return ResourceManager.GetString("Error_EventManagerReturnedByEventServiceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Event is null..
        /// </summary>
        internal static string Error_EventNameIsNull {
            get {
                return ResourceManager.GetString("Error_EventNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the EventTrigger is null..
        /// </summary>
        internal static string Error_EventTriggerNameIsNull {
            get {
                return ResourceManager.GetString("Error_EventTriggerNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EventTrigger &apos;{0}&apos; already has been added to an EventManager..
        /// </summary>
        internal static string Error_EventTriggerXAlreadyAddedToAnEventManager {
            get {
                return ResourceManager.GetString("Error_EventTriggerXAlreadyAddedToAnEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event &apos;{0}&apos; already has been added to an EventManager..
        /// </summary>
        internal static string Error_EventXAlreadyAddedToAnEventManager {
            get {
                return ResourceManager.GetString("Error_EventXAlreadyAddedToAnEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Event &apos;{0}&apos; doesn&apos;t exist in the EventManager..
        /// </summary>
        internal static string Error_EventXDoesNotExistInEventManager {
            get {
                return ResourceManager.GetString("Error_EventXDoesNotExistInEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor number &apos;{0} is invalid. Only values from 0 to {1} are valid..
        /// </summary>
        internal static string Error_FloorXIsInvalidFloorCountY {
            get {
                return ResourceManager.GetString("Error_FloorXIsInvalidFloorCountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IEventManagerService is missing. This is required for this operation..
        /// </summary>
        internal static string Error_IEventManagerServiceIsMissing {
            get {
                return ResourceManager.GetString("Error_IEventManagerServiceIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The LongTermEvent is required to be added to an EventManager.&quot;.
        /// </summary>
        internal static string Error_LongTermEventRequiresEventManager {
            get {
                return ResourceManager.GetString("Error_LongTermEventRequiresEventManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an Event with the name &apos;{0}&apos;. Events must have unique names..
        /// </summary>
        internal static string Error_ThereAlreadyExistsAnEventNamedX {
            get {
                return ResourceManager.GetString("Error_ThereAlreadyExistsAnEventNamedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an EventTrigger with the name &apos;{0}&apos;. EventTriggers must have unique names..
        /// </summary>
        internal static string Error_ThereAlreadyExistsAnEventTriggerNamedX {
            get {
                return ResourceManager.GetString("Error_ThereAlreadyExistsAnEventTriggerNamedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        internal static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        internal static string PleaseEnterName {
            get {
                return ResourceManager.GetString("PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        internal static string PropCate_Identification {
            get {
                return ResourceManager.GetString("PropCate_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PropCate_Settings {
            get {
                return ResourceManager.GetString("PropCate_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area in which the AreaEventTrigger may get triggered..
        /// </summary>
        internal static string PropDesc_AET_Area {
            get {
                return ResourceManager.GetString("PropDesc_AET_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area in which the AreaEventTrigger may get triggered (in tile-space)..
        /// </summary>
        internal static string PropDesc_AET_TileArea {
            get {
                return ResourceManager.GetString("PropDesc_AET_TileArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event that gets triggered when the DualSwitchEvent is triggered and the IsSwitched flag is false..
        /// </summary>
        internal static string PropDesc_DSEvent_EventOff {
            get {
                return ResourceManager.GetString("PropDesc_DSEvent_EventOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event that gets triggered when the DualSwitchEvent is triggered and the IsSwitched flag is true..
        /// </summary>
        internal static string PropDesc_DSEvent_EventOn {
            get {
                return ResourceManager.GetString("PropDesc_DSEvent_EventOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the DualSwitchEvent can be switched on or off...
        /// </summary>
        internal static string PropDesc_DSEvent_IsSwitchable {
            get {
                return ResourceManager.GetString("PropDesc_DSEvent_IsSwitchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the DualSwitchEvent is initially in a switched state or not..
        /// </summary>
        internal static string PropDesc_DSEvent_IsSwitched {
            get {
                return ResourceManager.GetString("PropDesc_DSEvent_IsSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (unique) name of the Event. .
        /// </summary>
        internal static string PropDesc_E_Name {
            get {
                return ResourceManager.GetString("PropDesc_E_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event which gets triggered when the EventTrigger is triggered..
        /// </summary>
        internal static string PropDesc_ET_Event {
            get {
                return ResourceManager.GetString("PropDesc_ET_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the EventTrigger is initially in an active state or not. Only active Triggers can get triggered..
        /// </summary>
        internal static string PropDesc_ET_IsActive {
            get {
                return ResourceManager.GetString("PropDesc_ET_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The (unique) name of the EventTrigger..
        /// </summary>
        internal static string PropDesc_ET_Name {
            get {
                return ResourceManager.GetString("PropDesc_ET_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor this Object is part of..
        /// </summary>
        internal static string PropDesc_Floor {
            get {
                return ResourceManager.GetString("PropDesc_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of events this MultiEvent delegates all calls to Trigger to..
        /// </summary>
        internal static string PropDesc_MultiEvent_Events {
            get {
                return ResourceManager.GetString("PropDesc_MultiEvent_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event that gets triggered after Time seconds after the TimedEvent was triggered..
        /// </summary>
        internal static string PropDesc_TimedEvent_Event {
            get {
                return ResourceManager.GetString("PropDesc_TimedEvent_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time in seconds until the TimedEvent delegates a Trigger call onto the Event..
        /// </summary>
        internal static string PropDesc_TimedEvent_Time {
            get {
                return ResourceManager.GetString("PropDesc_TimedEvent_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies type information about the Object..
        /// </summary>
        internal static string PropDesc_TypeName {
            get {
                return ResourceManager.GetString("PropDesc_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Area.
        /// </summary>
        internal static string PropDisp_AET_Area {
            get {
                return ResourceManager.GetString("PropDisp_AET_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Area (in tile-space).
        /// </summary>
        internal static string PropDisp_AET_TileArea {
            get {
                return ResourceManager.GetString("PropDisp_AET_TileArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event (when disabled).
        /// </summary>
        internal static string PropDisp_DSEvent_EventOff {
            get {
                return ResourceManager.GetString("PropDisp_DSEvent_EventOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event (when enabled).
        /// </summary>
        internal static string PropDisp_DSEvent_EventOn {
            get {
                return ResourceManager.GetString("PropDisp_DSEvent_EventOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Switchable.
        /// </summary>
        internal static string PropDisp_DSEvent_IsSwitchable {
            get {
                return ResourceManager.GetString("PropDisp_DSEvent_IsSwitchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Switched.
        /// </summary>
        internal static string PropDisp_DSEvent_IsSwitched {
            get {
                return ResourceManager.GetString("PropDisp_DSEvent_IsSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string PropDisp_Event {
            get {
                return ResourceManager.GetString("PropDisp_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string PropDisp_Floor {
            get {
                return ResourceManager.GetString("PropDisp_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string PropDisp_IsActive {
            get {
                return ResourceManager.GetString("PropDisp_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string PropDisp_MultiEvent_Events {
            get {
                return ResourceManager.GetString("PropDisp_MultiEvent_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PropDisp_Name {
            get {
                return ResourceManager.GetString("PropDisp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string PropDisp_TimedEvent_Event {
            get {
                return ResourceManager.GetString("PropDisp_TimedEvent_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string PropDisp_TimedEvent_Time {
            get {
                return ResourceManager.GetString("PropDisp_TimedEvent_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        internal static string PropDisp_TypeName {
            get {
                return ResourceManager.GetString("PropDisp_TypeName", resourceCulture);
            }
        }
    }
}
