// <auto-generated />

namespace Atom.ErrorReporting.Dialogs
{
    partial class ExceptionDetailsDialog
    {
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.treeViewStackTrace = new System.Windows.Forms.TreeView();
            this.SuspendLayout();
            // 
            // treeViewStackTrace
            // 
            this.treeViewStackTrace.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeViewStackTrace.Location = new System.Drawing.Point( 0, 0 );
            this.treeViewStackTrace.Name = "treeViewStackTrace";
            this.treeViewStackTrace.Size = new System.Drawing.Size( 509, 462 );
            this.treeViewStackTrace.TabIndex = 5;
            // 
            // ExceptionDetailsDialog
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF( 6F, 13F );
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size( 509, 462 );
            this.Controls.Add( this.treeViewStackTrace );
            this.Name = "ExceptionDetailsDialog";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Stack Trace";
            this.ResumeLayout( false );

        }

        #endregion

        private System.Windows.Forms.TreeView treeViewStackTrace;
    }
}