// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser (Tick)</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.ErrorReporting.Dialogs" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.ErrorReporting.Errors" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.ErrorReporting.Hooks" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.ErrorReporting.Reporters" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.ErrorReporting.Formatters" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope="type", Target="Atom.ErrorReporting.IErrorFactory" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="MailTo", Scope="member", Target="Atom.ErrorReporting.Reporters.BaseMailErrorReporter.#.ctor(System.String,System.String,Atom.Mail.IMailSender)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Multi", Scope="type", Target="Atom.ErrorReporting.Formatters.MultiErrorMessageFormatter" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope="type", Target="Atom.ErrorReporting.Formatters.MultiErrorMessageFormatter" )]
