// <auto-generated />

namespace Atom.Events.Design
{
    partial class EventSelectionOrCreationDialog
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose( bool disposing )
        {
            if( disposing && (components != null) )
            {
                components.Dispose();
            }
            base.Dispose( disposing );
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.buttonSelectExisting = new System.Windows.Forms.Button();
            this.buttonCreateNew = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // buttonSelectExisting
            // 
            this.buttonSelectExisting.Location = new System.Drawing.Point( 12, 12 );
            this.buttonSelectExisting.Name = "buttonSelectExisting";
            this.buttonSelectExisting.Size = new System.Drawing.Size( 124, 23 );
            this.buttonSelectExisting.TabIndex = 0;
            this.buttonSelectExisting.Text = "Select Existing";
            this.buttonSelectExisting.UseVisualStyleBackColor = true;
            this.buttonSelectExisting.Click += new System.EventHandler( this.OnSelectButtonClicked );
            // 
            // buttonCreateNew
            // 
            this.buttonCreateNew.Location = new System.Drawing.Point( 12, 44 );
            this.buttonCreateNew.Name = "buttonCreateNew";
            this.buttonCreateNew.Size = new System.Drawing.Size( 124, 23 );
            this.buttonCreateNew.TabIndex = 1;
            this.buttonCreateNew.Text = "Create New";
            this.buttonCreateNew.UseVisualStyleBackColor = true;
            this.buttonCreateNew.Click += new System.EventHandler( this.OnCreateButtonClicked );
            // 
            // buttonCancel
            // 
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point( 12, 93 );
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size( 124, 23 );
            this.buttonCancel.TabIndex = 2;
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            // 
            // EventSelectionOrCreationDialog
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF( 6F, 13F );
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.buttonCancel;
            this.ClientSize = new System.Drawing.Size( 148, 128 );
            this.ControlBox = false;
            this.Controls.Add( this.buttonCancel );
            this.Controls.Add( this.buttonCreateNew );
            this.Controls.Add( this.buttonSelectExisting );
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Name = "EventSelectionOrCreationDialog";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Select";
            this.ResumeLayout( false );

        }

        #endregion

        private System.Windows.Forms.Button buttonSelectExisting;
        private System.Windows.Forms.Button buttonCreateNew;
        private System.Windows.Forms.Button buttonCancel;
    }
}