//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Math.Graph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Math.Graph.GraphErrorStrings", typeof(GraphErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such an Edge already exists.
        /// </summary>
        internal static string EdgeAlreadyExists {
            get {
                return ResourceManager.GetString("EdgeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists an edge from Vertex &apos;{0}&apos; to Vertex &apos;{1}&apos;..
        /// </summary>
        internal static string EdgeAlreadyExistsFromXToY {
            get {
                return ResourceManager.GetString("EdgeAlreadyExistsFromXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data stored in an Edge of the Graph is null. This is invalid for this operation..
        /// </summary>
        internal static string EdgeDataIsNull {
            get {
                return ResourceManager.GetString("EdgeDataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge &lt;-&gt; Graph - IsDirected mismatch. A directed graph can only contain directed edges and visa versa..
        /// </summary>
        internal static string EdgeGraphDirectedMismatch {
            get {
                return ResourceManager.GetString("EdgeGraphDirectedMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires the Graphs to be both directed or undirected..
        /// </summary>
        internal static string GraphDirectionMismatch {
            get {
                return ResourceManager.GetString("GraphDirectionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Graph doesn&apos;t allow Edges that start and end at the same Vertex.  (Self Loops).
        /// </summary>
        internal static string GraphDoesntAllowSelfLoopAdded {
            get {
                return ResourceManager.GetString("GraphDoesntAllowSelfLoopAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Graph contains cycles. This is invalid for this operation..
        /// </summary>
        internal static string GraphHasCycles {
            get {
                return ResourceManager.GetString("GraphHasCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Graph is empty. This is invalid for this operation..
        /// </summary>
        internal static string GraphIsEmpty {
            get {
                return ResourceManager.GetString("GraphIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching Vertex has been found in the Graph..
        /// </summary>
        internal static string NoMatchingVertexFoundInGraph {
            get {
                return ResourceManager.GetString("NoMatchingVertexFoundInGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only valid on a directed Graph..
        /// </summary>
        internal static string OperationOnlyValidonDirectedGraph {
            get {
                return ResourceManager.GetString("OperationOnlyValidonDirectedGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only valid on simple graphs that contain no self-loops or multiple edges..
        /// </summary>
        internal static string OperationOnlyValidOnSimpleGraphs {
            get {
                return ResourceManager.GetString("OperationOnlyValidOnSimpleGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vertex already exists in the Graph..
        /// </summary>
        internal static string VertexAlreadyExistsInGraph {
            get {
                return ResourceManager.GetString("VertexAlreadyExistsInGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vertex could not be found..
        /// </summary>
        internal static string VertexCouldNotBeFound {
            get {
                return ResourceManager.GetString("VertexCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex-count is zero..
        /// </summary>
        internal static string VertexCountIsZero {
            get {
                return ResourceManager.GetString("VertexCountIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vertex is not part of the Edge..
        /// </summary>
        internal static string VertexNotPartOfEdge {
            get {
                return ResourceManager.GetString("VertexNotPartOfEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Voltage &apos;{0}&apos; of the Voltage Graph is not part of the Voltage Group of Order &apos;{1}&apos;..
        /// </summary>
        internal static string VoltageXOfVoltageGraphNotPartOfSpecifiedVoltageGroupOrderY {
            get {
                return ResourceManager.GetString("VoltageXOfVoltageGraphNotPartOfSpecifiedVoltageGroupOrderY", resourceCulture);
            }
        }
    }
}
