//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Math {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MathErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MathErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Math.MathErrorStrings", typeof(MathErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is expected to be between {0} and {1} (including {0} and {1})..
        /// </summary>
        public static string ArgumentInIntervalXYInclusive {
            get {
                return ResourceManager.GetString("ArgumentInIntervalXYInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given argument is infinite or NaN. This is not allowed..
        /// </summary>
        public static string ArgumentIsInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentIsInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given argument is too large for the set iteration limit..
        /// </summary>
        public static string ArgumentTooLargeForIterationLimit {
            get {
                return ResourceManager.GetString("ArgumentTooLargeForIterationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t receive the value. The vertex order is &apos;TurnDirection.None&apos;..
        /// </summary>
        public static string CantReceiveValueVertexOrderIsNone {
            get {
                return ResourceManager.GetString("CantReceiveValueVertexOrderIsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set the vertex order to &apos;TurnDirection.None&apos;..
        /// </summary>
        public static string CantSetVertexOrderToNone {
            get {
                return ResourceManager.GetString("CantSetVertexOrderToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the matrices is incompatible for this operation..
        /// </summary>
        public static string IncompatibleMatricesTimes {
            get {
                return ResourceManager.GetString("IncompatibleMatricesTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions mismatch. This operation requires the matrices to be of the same size..
        /// </summary>
        public static string MatrixDimensionsMismatch {
            get {
                return ResourceManager.GetString("MatrixDimensionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Matrix is singular/degenerated. (--&gt; The Matrix is not 	invertible).
        /// </summary>
        public static string MatrixIsSingular {
            get {
                return ResourceManager.GetString("MatrixIsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Matrix must be a square matrix..
        /// </summary>
        public static string MatrixMustBeSquare {
            get {
                return ResourceManager.GetString("MatrixMustBeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix must be symmetric..
        /// </summary>
        public static string MatrixMustBeSymmetric {
            get {
                return ResourceManager.GetString("MatrixMustBeSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Matrix must be symmetric positive definite for this operation..
        /// </summary>
        public static string MatrixMustBeSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("MatrixMustBeSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not positive definite..
        /// </summary>
        public static string MatrixNotPositiveDefinite {
            get {
                return ResourceManager.GetString("MatrixNotPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix&apos;s rank is not full..
        /// </summary>
        public static string MatrixRankIsNotFull {
            get {
                return ResourceManager.GetString("MatrixRankIsNotFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows of the Matrices doesn&apos;t match..
        /// </summary>
        public static string MatrixRowCountMismatch {
            get {
                return ResourceManager.GetString("MatrixRowCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions mismatch. This operation requires the matrix and the vector to be of the same size..
        /// </summary>
        public static string MatrixVectorDimensionsMismatch {
            get {
                return ResourceManager.GetString("MatrixVectorDimensionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plane distance {0} is negative. This is not supported..
        /// </summary>
        public static string NegativePlaneDistance {
            get {
                return ResourceManager.GetString("NegativePlaneDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is invalid on a 0-vector..
        /// </summary>
        public static string OperationInvalidOnZeroVector {
            get {
                return ResourceManager.GetString("OperationInvalidOnZeroVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires at least one point..
        /// </summary>
        public static string OperationRequiresAtleastOnePoint {
            get {
                return ResourceManager.GetString("OperationRequiresAtleastOnePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The near plane distance is larger than the far plane distance. This is not allowed..
        /// </summary>
        public static string OppositePlanes {
            get {
                return ResourceManager.GetString("OppositePlanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field of view value &apos;{0}&apos; is out of valid range of 0 and PI (180 degree)..
        /// </summary>
        public static string OutRangeFieldOfView {
            get {
                return ResourceManager.GetString("OutRangeFieldOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified angle &apos;{0}&apos; is greater than two Pi..
        /// </summary>
        public static string SpecifiedAngleXGreaterTwoPi {
            get {
                return ResourceManager.GetString("SpecifiedAngleXGreaterTwoPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangulation requires at least 3 vertices as its input..
        /// </summary>
        public static string TriangulationRequiresAtLeastThreeVertices {
            get {
                return ResourceManager.GetString("TriangulationRequiresAtLeastThreeVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value is greater than the maximum..
        /// </summary>
        public static string ValueGreaterThanMaximum {
            get {
                return ResourceManager.GetString("ValueGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given value is less than the minimum..
        /// </summary>
        public static string ValueLessThanMinimum {
            get {
                return ResourceManager.GetString("ValueLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector length mismatch. This operation only works with Vectors that have the same number of elements..
        /// </summary>
        public static string VectorLengthMismatch {
            get {
                return ResourceManager.GetString("VectorLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vector must have the same number of elements as the number of rows of the matrix..
        /// </summary>
        public static string VectorSizeMatrixRowCountMismatch {
            get {
                return ResourceManager.GetString("VectorSizeMatrixRowCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex count is zero..
        /// </summary>
        public static string VertexCountIsZero {
            get {
                return ResourceManager.GetString("VertexCountIsZero", resourceCulture);
            }
        }
    }
}
