// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Wpf.GameLoop.#Updated" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Acid.Wpf.Collections" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Wpf.Animation" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Wpf.Dialogs" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="XamlGeneratedNamespace" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Penner", Scope="member", Target="Atom.Wpf.Animation.Animator.#AnimatePenner(System.Windows.DependencyObject,System.Windows.DependencyProperty,Atom.Wpf.Animation.PennerEquation,System.Double,System.Int32,System.EventHandler)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Penner", Scope="type", Target="Atom.Wpf.Animation.PennerDoubleAnimation" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Penner", Scope="member", Target="Atom.Wpf.Animation.Animator.#AnimatePenner(System.Windows.DependencyObject,System.Windows.DependencyProperty,Atom.Wpf.Animation.PennerEquation,System.Nullable`1<System.Double>,System.Double,System.Int32,System.EventHandler)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope="member", Target="Atom.Wpf.Animation.PennerDoubleAnimation.#GetCurrentValueCore(System.Double,System.Double,System.Windows.Media.Animation.AnimationClock)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerDoubleAnimation.#QuintEaseIn(System.Double,System.Double,System.Double,System.Double)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerDoubleAnimation.#QuintEaseInOut(System.Double,System.Double,System.Double,System.Double)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerDoubleAnimation.#QuintEaseOut(System.Double,System.Double,System.Double,System.Double)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerDoubleAnimation.#QuintEaseOutIn(System.Double,System.Double,System.Double,System.Double)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Penner", Scope="type", Target="Atom.Wpf.Animation.PennerEquation" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerEquation.#QuintEaseIn" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerEquation.#QuintEaseInOut" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerEquation.#QuintEaseOut" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Penner", Scope="type", Target="Atom.Wpf.Animation.PennerEquationTypeConverter" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Quint", Scope="member", Target="Atom.Wpf.Animation.PennerEquation.#QuintEaseOutIn" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#OnScAlphaChanged(System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#OnScBlueChanged(System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#OnScGreenChanged(System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#OnScRedChanged(System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScAlpha" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScAlphaProperty" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScBlue" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScBlueProperty" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScGreen" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScRed" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScRedProperty" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId="Sc", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#ScGreenProperty" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.ColorSpectrumSlider.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.ColorThumb.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.NumericUpDown.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope="member", Target="Atom.Wpf.Controls.NumericUpDown.#Value" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope="member", Target="Atom.Wpf.Controls.PropertyGridControl.#SelectedObject" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.RectangleInputControl.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope="member", Target="Atom.Wpf.Controls.RectangleInputControl.#Value" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.Vector2InputControl.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope="member", Target="Atom.Wpf.Controls.Vector2InputControl.#Value" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="X", Scope="member", Target="Atom.Wpf.Controls.Vector2InputControl.#X" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Y", Scope="member", Target="Atom.Wpf.Controls.Vector2InputControl.#Y" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope="member", Target="Atom.Wpf.Dialogs.ColorPickerDialog.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope="member", Target="Atom.Wpf.Dialogs.OverwritePromptDialog.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope="member", Target="Atom.Wpf.Controls.ColorPicker.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope="member", Target="Atom.Wpf.SafeExecute.#WithMsgBox(System.Action)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope="member", Target="Atom.Wpf.LambdaCommand.#.ctor(System.Action`1<System.Object>,System.Func`2<System.Object,System.Boolean>)" )]
