// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#ColorValue" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Inception" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Momentum" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Position" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Rotation" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Scale" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Velocity" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2105:ArrayFieldsShouldNotBeReadOnly", Scope="member", Target="Atom.Xna.Particles.Particle.#VertexElements" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Particle.#Age" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage", "CA2207:InitializeValueTypeStaticFieldsInline", Scope="member", Target="Atom.Xna.Particles.Particle.#.cctor()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.Particles.Particle.#ApplyForce(Microsoft.Xna.Framework.Vector2&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.Particles" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1021:AvoidOutParameters", MessageId="1#", Scope="member", Target="Atom.Xna.Particles.Emitter.#GenerateParticleForce(Microsoft.Xna.Framework.Vector2&,Microsoft.Xna.Framework.Vector2&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="0#", Scope="member", Target="Atom.Xna.Particles.Emitter.#GenerateParticleForce(Microsoft.Xna.Framework.Vector2&,Microsoft.Xna.Framework.Vector2&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="1#", Scope="member", Target="Atom.Xna.Particles.Emitter.#GenerateParticleOffset(System.Single,Microsoft.Xna.Framework.Vector2&,Microsoft.Xna.Framework.Vector2&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1021:AvoidOutParameters", MessageId="2#", Scope="member", Target="Atom.Xna.Particles.Emitter.#GenerateParticleOffset(System.Single,Microsoft.Xna.Framework.Vector2&,Microsoft.Xna.Framework.Vector2&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#Budget" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope="member", Target="Atom.Xna.Particles.Emitter.#Modifiers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#Modifiers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope="member", Target="Atom.Xna.Particles.Emitter.#Modifiers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#Particles" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ParticleTexture" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope="member", Target="Atom.Xna.Particles.Emitter.#Rand" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseColor" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseOpacity" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseQuantity" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseRotation" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseScale" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseSpeed" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#Term" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#Triggers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId="2#", Scope="member", Target="Atom.Xna.Particles.Modifier.#Process(System.Single,System.Single,Atom.Xna.Particles.Particle&)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope="member", Target="Atom.Xna.Particles.Emitter.#Triggers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.Particles.Renderers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Renderers", Scope="namespace", Target="Atom.Xna.Particles.Renderers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Renderer", Scope="type", Target="Atom.Xna.Particles.Renderers.PointSpriteParticleRenderer" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Renderer", Scope="type", Target="Atom.Xna.Particles.ParticleRenderer" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Xna.Particles" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Xna.Particles.Renderers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="vorticity", Scope="member", Target="Atom.Xna.Particles.Modifiers.VortexModifier.#.ctor(Microsoft.Xna.Framework.Vector2,System.Single,System.Single,Atom.Math.TurnDirection)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="renderer", Scope="member", Target="Atom.Xna.Particles.ParticleEffect.#.ctor(Atom.Xna.Particles.ParticleRenderer)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="y", Scope="member", Target="Atom.Xna.Particles.Emitter.#Trigger(System.Single,System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="x", Scope="member", Target="Atom.Xna.Particles.Emitter.#Trigger(System.Single,System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="butget", Scope="member", Target="Atom.Xna.Particles.Emitter.#.ctor(System.Int32,System.Single)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.Particles.Modifiers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.Particles.Emitters" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Xna", Scope="namespace", Target="Atom.Xna.Particles.Controllers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Vorticity", Scope="member", Target="Atom.Xna.Particles.Modifiers.VortexModifier.#Vorticity" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Modifiers.RadialGravityModifier.#Strength" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Modifiers.LinearGravityModifier.#Gravity" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Atom.Xna.Particles.Controllers.BaseTriggerController.#GetTriggerPosition()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope="namespace", Target="Atom.Xna.Particles.Controllers" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="Atom.Xna.Particles.Emitter.#ReleaseColorValue" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope="member", Target="Atom.Xna.Particles.Modifier.#Rand" )]
