// <copyright file="GlobalSuppressions.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 
// </summary>
// <author>Paul Ennemoser (Tick)</author>
// <auto-generated />

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope="member", Target="Atom.Waypoints.PathSegment.#Atom.IOwnedBy`1<Atom.Math.Graph.Edge`2<Atom.Waypoints.Waypoint,Atom.Waypoints.PathSegment>>.Owner" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Atom.Waypoints.PathSegment.#GetLine()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope="member", Target="Atom.Waypoints.Waypoint.#Atom.IOwnedBy`1<Atom.Math.Graph.Vertex`2<Atom.Waypoints.Waypoint,Atom.Waypoints.PathSegment>>.Owner" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope="type", Target="Atom.Waypoints.WaypointGraph" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId="graph", Scope="member", Target="Atom.Waypoints.WaypointMap.#.ctor(Atom.Waypoints.IWaypointGraphDataFactory)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope="member", Target="Atom.Waypoints.WaypointMap.#RemoveWaypoint(Atom.Waypoints.Waypoint,System.Boolean)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Waypoints.WaypointMap.#PathSegmentAdded" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Waypoints.WaypointMap.#PathSegmentRemoved" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Waypoints.WaypointMap.#WaypointAdded" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope="member", Target="Atom.Waypoints.WaypointMap.#WaypointRemoved" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope="type", Target="Atom.Waypoints.IWaypointGraphDataFactory" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope="member", Target="Atom.Waypoints.WaypointMap.#Initialize(Atom.Math.Vector2,System.Int32)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="Atom.Waypoints.TilePathSegment.#GetTilePath()" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope="type", Target="Atom.Waypoints.Path" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope="member", Target="Atom.Waypoints.WaypointGraphDataFactory.#Instance" )]
