//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unhandled exception has occurred. ähnelt.
        /// </summary>
        public static string AnUnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("AnUnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified arguments may not be equal. ähnelt.
        /// </summary>
        public static string ArgumentsMayNotBeEqual {
            get {
                return ResourceManager.GetString("ArgumentsMayNotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The length of the array is out of valid range. ähnelt.
        /// </summary>
        public static string ArrayLengthOutOfValidRange {
            get {
                return ResourceManager.GetString("ArrayLengthOutOfValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The length of the array is out of valid range. ähnelt.
        /// </summary>
        public static string ArrayLengthOutOfValidRange1 {
            get {
                return ResourceManager.GetString("ArrayLengthOutOfValidRange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attempted to return an inactive Node to the Atom.Collections.Pool. ähnelt.
        /// </summary>
        public static string AttemptToReturnInActiveNode {
            get {
                return ResourceManager.GetString("AttemptToReturnInActiveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s not allowed to insert an item into the SortableList if KeepSorted is true. ähnelt.
        /// </summary>
        public static string CantInsertItemIntoSortableListIfKeepSortedIsTrue {
            get {
                return ResourceManager.GetString("CantInsertItemIntoSortableListIfKeepSortedIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The IEntityComponentCollection is read-only. As such this operation is invalid. ähnelt.
        /// </summary>
        public static string ComponentCollectionIsReadOnly {
            get {
                return ResourceManager.GetString("ComponentCollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The component of type &apos;{0}&apos; could not be found. ähnelt.
        /// </summary>
        public static string ComponentWasNotFound {
            get {
                return ResourceManager.GetString("ComponentWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A critical unhandled exception has occurred. ähnelt.
        /// </summary>
        public static string CriticalUnhandledExceptionHasOccurred {
            get {
                return ResourceManager.GetString("CriticalUnhandledExceptionHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity &apos;{0}&apos; already has been added to a scene. ähnelt.
        /// </summary>
        public static string EntityAlreadyAddedToScene {
            get {
                return ResourceManager.GetString("EntityAlreadyAddedToScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given IEntityComponentCollection is not owned by this Entity. This is invalid. ähnelt.
        /// </summary>
        public static string EntityComponentCollectionIsOwnedByDifferentEntity {
            get {
                return ResourceManager.GetString("EntityComponentCollectionIsOwnedByDifferentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity is required to have a component of type {0}. ähnelt.
        /// </summary>
        public static string EntityIsRequiredToHaveComponentType {
            get {
                return ResourceManager.GetString("EntityIsRequiredToHaveComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity &apos;{0}&apos; is currently not part of any scene. ähnelt.
        /// </summary>
        public static string EntityNotPartOfAScene {
            get {
                return ResourceManager.GetString("EntityNotPartOfAScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected different number of elements in the string &apos;{0}&apos; separated by &apos;{1}&apos;. Got &apos;{2}&apos; instead of &apos;{3}&apos;. ähnelt.
        /// </summary>
        public static string ExpectedDifferentNumberOfElementsInStringXSeparatedByYGotZInsteadOfW {
            get {
                return ResourceManager.GetString("ExpectedDifferentNumberOfElementsInStringXSeparatedByYGotZInsteadOfW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Node. The node&apos;s internal node index is out of range. ähnelt.
        /// </summary>
        public static string InvalidInternalNodeIndex {
            get {
                return ResourceManager.GetString("InvalidInternalNodeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Node. The  Pool of the Atom.Collections.PoolNode doesn&apos;t equal this Pool. ähnelt.
        /// </summary>
        public static string InvalidNodePoolMismatch {
            get {
                return ResourceManager.GetString("InvalidNodePoolMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Heap is empty. This is invalid for this operation. ähnelt.
        /// </summary>
        public static string InvalidOperationHeapIsEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationHeapIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid string format. Expected a string in the format &apos;{0}&apos;, separated by &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string InvalidStringFormatXWithSeparatorY {
            get {
                return ResourceManager.GetString("InvalidStringFormatXWithSeparatorY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string &apos;{0}&apos; has an invalid format. The expected format &apos;{1}&apos;, separated by &apos;{2}&apos;. ähnelt.
        /// </summary>
        public static string InvalidStringXFormatYWithSeparatorZ {
            get {
                return ResourceManager.GetString("InvalidStringXFormatYWithSeparatorZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item does not fulfill the predicate. ähnelt.
        /// </summary>
        public static string ItemDoesNotFulfillPredicate {
            get {
                return ResourceManager.GetString("ItemDoesNotFulfillPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list already contains the specified item. ähnelt.
        /// </summary>
        public static string ListAlreadyConstainsSpecifiedItem {
            get {
                return ResourceManager.GetString("ListAlreadyConstainsSpecifiedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t delete the last column of the Matrix. ähnelt.
        /// </summary>
        public static string MatrixDeleteOnlyColumn {
            get {
                return ResourceManager.GetString("MatrixDeleteOnlyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t delete the last row of the Matrix. ähnelt.
        /// </summary>
        public static string MatrixDeleteOnlyRow {
            get {
                return ResourceManager.GetString("MatrixDeleteOnlyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Maybe{T} instance has no value. ähnelt.
        /// </summary>
        public static string MaybeHasNoValue {
            get {
                return ResourceManager.GetString("MaybeHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Information ähnelt.
        /// </summary>
        public static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The source array must have at least as many elements as the specified size. ähnelt.
        /// </summary>
        public static string NotEnoughSpaceInSourceArray {
            get {
                return ResourceManager.GetString("NotEnoughSpaceInSourceArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is not enough space in the targeted array. ähnelt.
        /// </summary>
        public static string NotEnoughSpaceInTargetArray {
            get {
                return ResourceManager.GetString("NotEnoughSpaceInTargetArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The object {0} doesn&apos;t implement &apos;{1}&apos;. This is required. ähnelt.
        /// </summary>
        public static string ObjectXDoesntImplementY {
            get {
                return ResourceManager.GetString("ObjectXDoesntImplementY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occurred while parsing the given string &apos;{0}&apos;. Not enough entries. Expected &apos;{1}&apos;. Has &apos;{2}&apos;. ähnelt.
        /// </summary>
        public static string ParsingGivenStringXNotEnoughEntriesExpectedYHasZ {
            get {
                return ResourceManager.GetString("ParsingGivenStringXNotEnoughEntriesExpectedYHasZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service {0} could not be found. ähnelt.
        /// </summary>
        public static string ServiceXNotFound {
            get {
                return ResourceManager.GetString("ServiceXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified IEnumerable doesn&apos;t contain any elements. This is required. ähnelt.
        /// </summary>
        public static string SpecifiedEnumerableContainsNoElements {
            get {
                return ResourceManager.GetString("SpecifiedEnumerableContainsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified index is invalid. ähnelt.
        /// </summary>
        public static string SpecifiedIndexIsInvalid {
            get {
                return ResourceManager.GetString("SpecifiedIndexIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified index is out of valid range. ähnelt.
        /// </summary>
        public static string SpecifiedIndexIsOutOfValidRange {
            get {
                return ResourceManager.GetString("SpecifiedIndexIsOutOfValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified item is null. ähnelt.
        /// </summary>
        public static string SpecifiedItemIsNull {
            get {
                return ResourceManager.GetString("SpecifiedItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value is invalid. ähnelt.
        /// </summary>
        public static string SpecifiedValueIsInvalid {
            get {
                return ResourceManager.GetString("SpecifiedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value is Not a Number. This is invalid for this operation. ähnelt.
        /// </summary>
        public static string SpecifiedValueIsNaN {
            get {
                return ResourceManager.GetString("SpecifiedValueIsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value is negative. This is invalid for this operation. ähnelt.
        /// </summary>
        public static string SpecifiedValueIsNegative {
            get {
                return ResourceManager.GetString("SpecifiedValueIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value is zero. This is invalid for this operation. ähnelt.
        /// </summary>
        public static string SpecifiedValueIsZero {
            get {
                return ResourceManager.GetString("SpecifiedValueIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value is zero or negative. This is invalid for this operation. ähnelt.
        /// </summary>
        public static string SpecifiedValueIsZeroOrNegative {
            get {
                return ResourceManager.GetString("SpecifiedValueIsZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified value must be within the range zero .. one. ähnelt.
        /// </summary>
        public static string SpecifiedValueMustBeWithinRangeZeroOne {
            get {
                return ResourceManager.GetString("SpecifiedValueMustBeWithinRangeZeroOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The underlying property is read-only. As such the value of the property can&apos;t be changed. ähnelt.
        /// </summary>
        public static string TheUnderlyingPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("TheUnderlyingPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; has no public constructors. This is required. ähnelt.
        /// </summary>
        public static string TypeHasNoPublicConstructors {
            get {
                return ResourceManager.GetString("TypeHasNoPublicConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type &apos;{0}&apos; has no public constructor with &apos;{1}&apos; parameters. This is required. ähnelt.
        /// </summary>
        public static string TypeHasNoPublicConstructorWithParameters {
            get {
                return ResourceManager.GetString("TypeHasNoPublicConstructorWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Type of the given Object is not supported by this IObjectPropertyWrapper. ähnelt.
        /// </summary>
        public static string TypeNotSupportedByPropertyWrapper {
            get {
                return ResourceManager.GetString("TypeNotSupportedByPropertyWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type {0} doesn&apos;t implement &apos;{1}&apos;. This is required. ähnelt.
        /// </summary>
        public static string TypeXDoesntImplementY {
            get {
                return ResourceManager.GetString("TypeXDoesntImplementY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unhandled exception has occurred. ähnelt.
        /// </summary>
        public static string UnhandledExceptionHasOccurred {
            get {
                return ResourceManager.GetString("UnhandledExceptionHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version &apos;{0}&apos; of type {1} is not supported. Expected &apos;{2}&apos;. ähnelt.
        /// </summary>
        public static string VersionXOfTypeYIsNotSupportedExpectedZ {
            get {
                return ResourceManager.GetString("VersionXOfTypeYIsNotSupportedExpectedZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version &apos;{0}&apos; of type {1} is not supported. Expected &apos;{2} to {3}&apos;. ähnelt.
        /// </summary>
        public static string VersionXOfTypeYIsNotSupportedExpectedZToW {
            get {
                return ResourceManager.GetString("VersionXOfTypeYIsNotSupportedExpectedZToW", resourceCulture);
            }
        }
    }
}
