// <copyright file="SimpleEventHandler.cs" company="federrot Software">
//     Copyright (c) federrot Software. All rights reserved.
// </copyright>
// <summary>
//     Defines the Atom.SimpleEventHandler{TSender} delegate.
// </summary>
// <author>
//     Paul Ennemoser
// </author>

namespace Atom
{
    using System;

    /// <summary>
    /// Represents a typed handler for an event that doesn't contain special event data.
    /// </summary>
    /// <typeparam name="TSender">
    /// The type of the event data generated by the event.
    /// </typeparam>
    /// <param name="sender">
    /// The source of the event.
    /// </param>
    [Serializable]
    public delegate void SimpleEventHandler<TSender>( TSender sender );
}